version: '2'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iotube_validator
    volumes:
      - ./postgres:/var/lib/postgresql/data

  iotube-validator-api:
    container_name: iotube-validator-api
    image: $IMAGE
    restart: always
    ports:
      - 8081:8081
      - 8080:8080
    env_file:
      - env-db
    depends_on:
      - postgres
    volumes:
      - ./conf/api.yaml:/etc/iotube/api.yaml:ro
    command: validator -api /etc/iotube/api.yaml
  
  iotube-validator-monitor:
    container_name: iotube-validator-monitor
    image: $IMAGE
    restart: always
    depends_on:
      - postgres
    env_file:
      - env-db
    volumes:
      - ./conf/monitor.yaml:/etc/iotube/monitor.yaml:ro
    command: validator -monitor /etc/iotube/monitor.yaml

  iotube-validator-signer:
    container_name: iotube-validator-signer
    image: $IMAGE
    restart: always
    env_file:
      - env-db
    depends_on:
      - postgres
    volumes:
      - ./conf/signer.yaml:/etc/iotube/signer.yaml:ro
    command: validator -signer /etc/iotube/signer.yaml
