version: '2'

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    command: ["postgres", "-cshared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_USER: iotube-validator
      POSTGRES_PASSWORD: iotube-validator
      POSTGRES_DB: iotube-validator
    volumes:
      - ./postgres:/var/lib/postgresql/data

  iotube-validator-api:
    container_name: iotube-validator-api
    image: iotexdev/iotube-validator-service:latest
    restart: always
    ports:
      - 8081:8081
      - 8080:8080
    environment:
      VALIDATOR_DB_URL: 'postgresql://iotube-validator:iotube-validator@postgres:5432/iotube-validator'
      VALIDATOR_PRIVATE_KEY: ''
      MONITOR_DB_URL: 'postgresql://iotube-validator:iotube-validator@postgres:5432/iotube-validator'
    depends_on:
      - postgres
    volumes:
      - ./conf/api.yaml:/etc/iotube/api.yaml:ro
    command: validator -api /etc/iotube/api.yaml
  
  iotube-validator-monitor:
    container_name: iotube-validator-monitor
    image: iotexdev/iotube-validator-service:latest
    restart: always
    depends_on:
      - postgres
    environment:
      VALIDATOR_DB_URL: 'postgresql://iotube-validator:iotube-validator@postgres:5432/iotube-validator'
      VALIDATOR_PRIVATE_KEY: ''
      MONITOR_DB_URL: 'postgresql://iotube-validator:iotube-validator@postgres:5432/iotube-validator'
    volumes:
      - ./conf/monitor.yaml:/etc/iotube/monitor.yaml:ro
    command: validator -monitor /etc/iotube/monitor.yaml

  iotube-validator-signer:
    container_name: iotube-validator-signer
    image: iotexdev/iotube-validator-service:latest
    restart: always
    environment:
      VALIDATOR_DB_URL: 'postgresql://iotube-validator:iotube-validator@postgres:5432/iotube-validator'
      VALIDATOR_PRIVATE_KEY: ''
      MONITOR_DB_URL: 'postgresql://iotube-validator:iotube-validator@postgres:5432/iotube-validator'
    depends_on:
      - postgres
    volumes:
      - ./conf/signer.yaml:/etc/iotube/signer.yaml:ro
    command: validator -signer /etc/iotube/signer.yaml